// src/components/bento/LocationMap.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { IconMapPin, IconSun, IconMoon } from '@tabler/icons-svelte';
	import { browser } from '$app/environment';

	let mapContainer = $state<HTMLDivElement>();
	let leafletLoaded = $state(false);
	let mapInstance: any = null;
	let currentTime = $state('');
	let isDaytime = $state(true);
	const hometownCoords: [number, number] = [23.1815, 79.9864];
	const hometownTimezone = 'Asia/Kolkata';
	const hometownLabel = 'Jabalpur, IN';

	function updateTime() {
		const now = new Date();
		const localTime = new Intl.DateTimeFormat('en-US', {
			timeZone: hometownTimezone,
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit',
			hour12: false
		}).format(now);
		currentTime = localTime;

		// Check if daytime (6 AM - 9 PM)
		const hour = parseInt(localTime.split(':')[0]);
		isDaytime = hour >= 6 && hour < 21;
	}

	onMount(async () => {
		// Start clock
		updateTime();
		const interval = setInterval(updateTime, 1000);

		if (browser && mapContainer) {
			const L = (await import('leaflet')).default;
			await import('leaflet/dist/leaflet.css');
			mapInstance = L.map(mapContainer, {
				zoomControl: false,
				attributionControl: false,
				dragging: true,
				scrollWheelZoom: true,
				doubleClickZoom: true,
				boxZoom: true,
				keyboard: true,
				touchZoom: true
			}).setView(hometownCoords, 11);

			L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
				maxZoom: 19,
				attribution: '',
				keepBuffer: 4,
				updateWhenIdle: false,
				updateWhenZooming: false
			}).addTo(mapInstance);

			leafletLoaded = true;
		}

		return () => {
			clearInterval(interval);
		};
	});

	function recenterMap() {
		if (mapInstance) {
			mapInstance.setView(hometownCoords, 11);
		}
	}
</script>

<div class="border-surface0 bg-base flex flex-col rounded-xl border p-4 shadow-lg lg:col-span-1">
	<button
		onclick={recenterMap}
		class="text-text hover:text-accent mb-3 flex w-full cursor-pointer items-center gap-2 text-left text-sm font-semibold transition-colors"
	>
		<IconMapPin size={16} class="text-accent" />
		Currently Based In 📍
	</button>
	<div class="bg-surface0 relative w-full flex-1 overflow-hidden rounded-lg">
		{#if browser}
			<div bind:this={mapContainer} class="bg-surface0 h-full w-full"></div>
			{#if !leafletLoaded}
				<div class="bg-surface0 absolute inset-0 flex items-center justify-center">
					<span class="text-subtext1 text-xs">Loading map...</span>
				</div>
			{/if}
		{:else}
			<div class="absolute inset-0 flex items-center justify-center">
				<span class="text-subtext1 text-xs">Loading map...</span>
			</div>
		{/if}
	</div>
	<div class="mt-3 flex items-center justify-between gap-2">
		<button
			onclick={recenterMap}
			class="text-subtext0 hover:text-accent cursor-pointer text-xs whitespace-nowrap transition-colors"
		>
			{hometownLabel}
		</button>
		{#if currentTime}
			<div class="flex items-center gap-1">
				{#if isDaytime}
					<IconSun size={12} class="text-yellow" />
				{:else}
					<IconMoon size={12} class="text-blue" />
				{/if}
				<span class="text-accent font-mono text-xs whitespace-nowrap">
					{currentTime}
				</span>
			</div>
		{/if}
	</div>
</div>

<style>
	:global(.leaflet-container) {
		background: var(--color-base) !important;
	}

	:global(.leaflet-tile-container) {
		background: var(--color-base) !important;
	}

	:global(.leaflet-pane) {
		background: var(--color-base) !important;
	}
</style>

// src/components/bento/LocationMap.tsx
import React, { useEffect, useRef, useState } from 'react';
import { IconMapPin, IconSun, IconMoon } from '@tabler/icons-react';

export const LocationMap: React.FC = () => {
	const mapContainer = useRef<HTMLDivElement>(null);
	const [leafletLoaded, setLeafletLoaded] = useState(false);
	const [currentTime, setCurrentTime] = useState('');
	const [isDaytime, setIsDaytime] = useState(true);
	const mapInstanceRef = useRef<any>(null);

	const hometownCoords: [number, number] = [23.1815, 79.9864];
	const hometownTimezone = 'Asia/Kolkata';
	const hometownLabel = 'Jabalpur, IN';

	const updateTime = () => {
		const now = new Date();
		const localTime = new Intl.DateTimeFormat('en-US', {
			timeZone: hometownTimezone,
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit',
			hour12: false
		}).format(now);
		setCurrentTime(localTime);

		const hour = parseInt(localTime.split(':')[0]);
		setIsDaytime(hour >= 6 && hour < 21);
	};

	useEffect(() => {
		updateTime();
		const interval = setInterval(updateTime, 1000);

		const loadMap = async () => {
			if (typeof window !== 'undefined' && mapContainer.current) {
				const L = (await import('leaflet')).default;
				await import('leaflet/dist/leaflet.css');

				mapInstanceRef.current = L.map(mapContainer.current, {
					zoomControl: false,
					attributionControl: false,
					dragging: true,
					scrollWheelZoom: true,
					doubleClickZoom: true,
					boxZoom: true,
					keyboard: true,
					touchZoom: true
				}).setView(hometownCoords, 11);

				L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
					maxZoom: 19,
					attribution: '',
					keepBuffer: 4,
					updateWhenIdle: false,
					updateWhenZooming: false
				}).addTo(mapInstanceRef.current);

				setLeafletLoaded(true);
			}
		};

		loadMap();

		return () => {
			clearInterval(interval);
			if (mapInstanceRef.current) {
				mapInstanceRef.current.remove();
			}
		};
	}, []);

	const recenterMap = () => {
		if (mapInstanceRef.current) {
			mapInstanceRef.current.setView(hometownCoords, 11);
		}
	};

	return (
		<div className="border-surface0 bg-base flex flex-col rounded-xl border p-4 shadow-lg lg:col-span-1">
			<button
				onClick={recenterMap}
				className="text-text hover:text-accent mb-3 flex w-full cursor-pointer items-center gap-2 text-left text-sm font-semibold transition-colors"
			>
				<IconMapPin size={16} className="text-accent" />
				Currently Based In 📍
			</button>
			<div
				className="bg-surface0 relative w-full flex-1 overflow-hidden rounded-lg"
				style={{ minHeight: '200px' }}
			>
				<div ref={mapContainer} className="bg-surface0 h-full w-full" />
				{!leafletLoaded && (
					<div className="bg-surface0 absolute inset-0 flex items-center justify-center">
						<span className="text-subtext1 text-xs">Loading map...</span>
					</div>
				)}
			</div>
			<div className="mt-3 flex items-center justify-between gap-2">
				<button
					onClick={recenterMap}
					className="text-subtext0 hover:text-accent cursor-pointer text-xs whitespace-nowrap transition-colors"
				>
					{hometownLabel}
				</button>
				{currentTime && (
					<div className="flex items-center gap-1">
						{isDaytime ? (
							<IconSun size={12} className="text-yellow" />
						) : (
							<IconMoon size={12} className="text-blue" />
						)}
						<span className="text-accent font-mono text-xs whitespace-nowrap">{currentTime}</span>
					</div>
				)}
			</div>
		</div>
	);
};
